### ISSUE TITLE
Missing WebXRManager exports in r167

### ISSUE THREAD

**Issue by asyncore** [three-types/three-ts-types#1139]
PR #1079 seems to have removed the following export from `three.d.ts`
```
export * from "./renderers/webxr/WebXRManager.js";
```
Which causes missing `THREE.WebXRArrayCamera` and `THREE.WebXRManager` symbol errors in our codebase.

Do you know if the change was intentional?

**Comment by Methuselah96** [comment]
It was unintentional. The goal of that PR was to match the exports of three.js in order to avoid exporting more JS values from the main entry-point than three.js does, however I missed a few type-only exports that should still be exported.

https://github.com/three-types/three-ts-types/pull/1131 adds back some of the other type exports I missed. I'll work on creating a PR to add these back as well, or feel free to do it yourself if you beat me to it.
