### ISSUE TITLE
[@types/three] - most of the tests don't test types, they test the library

### ISSUE THREAD

**Issue by epreston** [three-types/three-ts-types#326]
Mirrored from: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64118

Question about testing for type definitions:

Very few of the tests for the "three" type definitions test the types.  Most of them are simple unit tests for the library itself.  

Is this correct ?

I would like to contribute but I would like to understand the expectations.  My understanding is that each test to should test the type definitions, expected types, return types.  It is not a unit test suite for the library.  

Only `three/test/core/core-eventDispatcher.ts` matches what I was expecting from type tests.  Everything else is just a unit test for the library itself.

**Comment by epreston** [comment]
Comparing this to tests in other type definitions, the tests should focus on testing the types rather than functionality of the library.  

Looking at the test runner, I don't see how it is actually executing the code since most tests don't check types.

**Comment by joshuaellis** [comment]
Hey @epreston thanks for raising this.

For some context, as you can imagine - the codebase is _huge_, so testing everything is very hard an unrealistic for individuals to do it immediately :) 

As you can also see we have a long list in `OTHER_FILES` which is generally not preferred by definitelyTyped so our current objective is to add some form of testing to those when the files are added / modified and the quickest way to do this is to use the `example` from three.

Totally agree, it's not the "right" test, but it does work to a certain extent.

Having said that, if you want to look at implementing the right kinds of tests then I would be more than welcome to it! And we'll try to support you along the way.

**Comment by epreston** [comment]
Hey Josh, the issue is the tests have nothing to do with testing the types.  

Most of the types have one issue or another because none of the testing is real.  I went through 3 files today, found an issue in each one.  Found a type module that was missing completely. It's been a sticky point during my last project.

I'll submit further updates to this repo.  Can we remove the fake tests (the majority) and get to work on nailing this down ?

**Comment by joshuaellis** [comment]
No I'm afraid we can't because it would mean we have to add the files back onto OTHER_FILES and I'd rather implement this gradually.

**Comment by epreston** [comment]
That makes no sense Josh and is off topic.  This is about the large number of tests which are fancy placeholders that don't test types.

On this other topic:

One type module was missing so I added it.  I noticed a list was being maintained of these types of modules in the "other_files" file.  I added an entry where it would go.  If you are not maintaining that file, which is missing several other entries, why not remove it ?

**Comment by epreston** [comment]
Please be clear, it's not that these are the wrong tests or a matter of complexity.  (Its not even a large library) The issue is they are the unit tests of the library, renamed with a `.ts` extension, and passed of as test for the type library.  It's pretend.  So most of the types have one issue or another.

Best path forward is to drop them, keeping only the real type tests, know where we stand, and get to work filling them in.

**Comment by Methuselah96** [comment]
Hey @epreston, welcome to the community!

As Josh has mentioned, maintaining the three.js types is not an easy task. The choice to use unit tests as a way of testing types is intentional and I believe it still has value. The goal is not to run the unit tests. The goal is to type-check the unit tests as an example of how the three.js types might be used in real life. They are type-checked by TypeScript, and while they don't have things like type assertions, it does ensure that methods exist and provide return values that can be used in real code.

I am not as active as @joshuaellis is in contributing regularly, so I'm not sure how helpful those types of tests are in practice. However, as Josh has mentioned, the current tests provide some value and we welcome contributions to provide tests that are closer to the style that you are describing. If/when we have enough of those tests, I imagine we could re-discuss whether the unit test style of tests is still providing value.

**Comment by epreston** [comment]
Hi Methuselah. Everyones task would be easier and more coordinated if the tests actually tested the types.

I get the spirit but its not moving this forward.  Aside from the poor outcomes, here's the issues with that line of thinking:
- They are type checked by typescript (by whom? when?) but go under the radar of the type testing framework and automated tooling ? 
- You say no type assertions but `three/test/core/core-eventDispatcher.ts` has a healthy number of them ? 
- You maintain a 60+ line test file which is lucky to exercise each type once, in one way, using code which often no longer works ?
- Type accuracy is the goal, what the code does means little.  If you have 5 lines of testing, that should be 5 valid method signatures; not boiler plate pasted from a unit test for a different purpose.

This is the opportunity to discuss it and clean it up.

**Comment by Methuselah96** [comment]
> They are type checked by typescript (by whom? when?) but go under the radar of the type testing framework and automated tooling ?

They should be tested by the testing framework and the automated tooling. If there is a type error in the tests, running either `yarn test` or `yarn test-all` should fail. This is run during the CI of each pull request, and so a pull request can't be merged unless the types pass. If this is not the case, we should definitely fix that.

> You say no type assertions but three/test/core/core-eventDispatcher.ts has a healthy number of them ?

I was describing the unit-test-style tests. By all means, let's create more test files like `core-eventDispatcher.ts`.

> You maintain a 60+ line test file which is lucky to exercise each type once, in one way, using code which often no longer works ?

It's not ideal, but I still believe it's better than no tests at all, and given our time constraints, that would be the likely alternative.

> Type accuracy is the goal, what the code does means little. If you have 5 lines of testing, that should be 5 valid method signatures; not boiler plate pasted from a unit test for a different purpose.

Let's do it!

We agree that adding tests that test the types explicitly would be beneficial. Where we probably disagree is that the unit-test-style tests that currently exist are actively making things worse. Using the existing unit tests from three.js was a low-cost way of getting some form of tests, even if they aren't ideal.

So please, add more tests that test the types explicitly. We just don't think that we can replace the value of the current unit-test-style tests overnight with explicit-type tests. That is why we are suggesting that this is done gradually instead of dropping the current form of testing. We are providing a path forward for you to implement the changes you are suggesting, but it's going to require you actually putting in the work.

**Comment by epreston** [comment]
Types are not tested in `https://github.com/DefinitelyTyped/DefinitelyTyped` that way.  Yes, this project is not getting the benefit of the tooling downstream.  I already have a path but, thank you for the offer.  I'd prefer to work in a way that is earnest about what is done and have accurate tooling.  Pretending to have tests for most things is confusing.

**Comment by joshuaellis** [comment]
Off the back of this issue for the most current additions i've added the starting block of "actually testing the types" you can see this here – https://github.com/three-types/three-ts-types/blob/master/types/three/test/helpers/helper-viewHelper.ts

Converting the current tests would be a great help / opportunity for individuals if anyone is interested.

**Comment by epreston** [comment]
Joshua, the greatest kindness and support I can offer is hard truths I've already laid down.  The code examples are often from many versions ago and they will continue to ensure that your efforts are inaccurate.  They give you, at best, one single line of testing on a given type module for 60+ lines of maintenance.  Drop them.  

The time to delete the file is nearly equal to creating its functional replacement.  I don't know its quicker to say delete everything but the target method signatures or delete the file and type out the 30 characters.  Wishing you the best in your endeavours.

**Comment by Methuselah96** [comment]
We have split the tests into ["unit" and "integration" tests](https://github.com/three-types/three-ts-types/issues/365) and also added a system where we keep the "integration" tests up-to-date with the latest three.js examples. I am of the opinion that our testing is adequate and am closing this for now.
