### ISSUE TITLE
Euler type does not match ThreeJs declaration

### ISSUE THREAD

**Issue by arcasoy** [three-types/three-ts-types#355]
-   `three` version: 0.149.0
-   `node` version: v18.12.1
-   `npm` version: 8.19.2

### Problem description:

- Typescript throwing type errors when using Euler._x, _y, and _z. in code.
- Three.js class is defined with _x, _y, and _z as the gettable and settable variables for an Euler, while the type definition expects x, y, z.

### Relevant code:

- Definition of [Euler class](https://github.com/mrdoob/three.js/blob/7da79d5d95839781dcbc54d341d0d7bf6d6dae44/src/math/Euler.js) from Three.js repo
- Definition of [Euler type](https://github.com/three-types/three-ts-types/blob/master/types/three/src/math/Euler.d.ts) from this repository

#### Example of where the error occurs:
```ts
function dampEuler(v: Euler, t: Euler, lambda: number, delta: number) {
  v.x = MathUtils.damp(v._x, t._x, lambda, delta);
  v.y = MathUtils.damp(v._y, t._y, lambda, delta);
  v.z = MathUtils.damp(v._z, t._z, lambda, delta);
}
```

### Suggested solution:

Redefine type with ._x, ._y, and ._z instead of x, y, z

**Comment by arcasoy** [comment]
@rafaelsc will you be handling the code change for this considering you referenced that larger PR or is that only documentation focused?

**Comment by Methuselah96** [comment]
I think they referenced this issue by mistake.

**Comment by Methuselah96** [comment]
I'm not quite sure I understand the issue. It seems like the three.js source code you linked to defines `x`, `y`, and `z` with getters/setters as the proper way of accessing those variables. The `_x`, `_y`, and `_z` variables are private variables that are not meant to be accessed directly by the user.

**Comment by arcasoy** [comment]
My issues lie in directly accessing the attributes. In my app, the Euler's are saved and upon reload get assigned to a variable of type Euler. When this occurs, the methods of the object are no longer part of the Euler, and instead only the data exists. Because of this, the getters and setters and no longer defined, and only the public variables `_x`, `_y`, and `_z` are accessible. 

I'm providing a screenshot of two Eulers, one of which is from the camera in the application so all the methods are there, while the other was saved to state before printed. To do a comparison between these two, it seems like I must access the `_` attributes, but the types argue that those attributes don't exist.
![image](https://user-images.githubusercontent.com/32803978/221294723-a55afde6-e01a-442f-8478-080b3726c0aa.png)

Specifically my goal is to run those two through the code in the original post to damp the Euler between two values.

**Comment by Methuselah96** [comment]
> In my app, the Euler's are saved and upon reload get assigned to a variable of type Euler.

It doesn't sound like it's actually an `Euler` then, it's just an object that contains (private and public) data of an `Euler` and not an instance of the `Euler` class. Is there a way for you to actually construct an `Euler` instead of only having an object with the underlying data?

If you have code demonstrating the issue, that would be helpful as well.

**Comment by arcasoy** [comment]
Unfortunately when the application saves, all data is stringifies and parsed when returned. The states, defined with TS as `thisIsAnEulerVar:Euler` are set to the values, but not instantiated on reload.

Perhaps it's a misunderstanding on my part, but I'm a little confused why you say that `_x`, `_y`, and `_z` are private in your comment above? [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) MDN lists private fields as those denoted with a `#`. Additionally, if these attributes were private, I don't see why I can clearly access them. My function above works with the `_`'s included, but TypeScript argues that the syntax is improper.

Additionally, the Three link I posted above only has `this._x`, `this._y`, and `this._z`, the `x`, `y`, and `z` are only methods, not class members. 

I have provided some code above where the issue occurs, but let me know what in specific you need in addition and I can try to provide it. Thanks for all of the help

**Comment by Methuselah96** [comment]
> Unfortunately when the application saves, all data is stringifies and parsed when returned. The states, defined with TS as `thisIsAnEulerVar:Euler` are set to the values, but not instantiated on reload.

Unfortunately `thisIsAnEulerVar` is incorrectly typed then, because it's not actually an `Euler`, it's just an object that contains the data that an `Euler` contains.

> Perhaps it's a misunderstanding on my part, but I'm a little confused why you say that `_x`, `_y`, and `_z` are private in your comment above? [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) MDN lists private fields as those denoted with a `#`. Additionally, if these attributes were private, I don't see why I can clearly access them. My function above works with the `_`'s included, but TypeScript argues that the syntax is improper.

The reason I keep calling them private is because the `_` dangle at the front of these class variables are an old convention for trying to signify that something is private and shouldn't be used by external users of the class. The MDN article you linked to describes a feature that was added in ES2022, and three.js is sticking to ES2018 for now (see https://github.com/mrdoob/three.js/pull/24237, https://github.com/mrdoob/three.js/pull/25168, and https://github.com/mrdoob/three.js/pull/25172), so it can't use that feature and has to rely on the `_` convention.

> Additionally, the Three link I posted above only has `this._x`, `this._y`, and `this._z`, the `x`, `y`, and `z` are only methods, not class members.

To be clear, the "methods" are [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) and [setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) and they are accessed as if it's just a normal class member (i.e., `euler.x`, etc.). See the MDN articles I linked to if you're not clear how that works.

> I have provided some code above where the issue occurs, but let me know what in specific you need in addition and I can try to provide it. Thanks for all of the help

Do you have the code where the Euler is being stringified/parsed? It seems like maybe you have some unsound types that are letting you assign a stringified/parsed `Euler` to the `Euler` type when doing so is actually incorrect.

Is there a way for you to define your own `Euler` interface that is just a simple object that has `x`/`y`/`z` properties that you could then instantiate an `Euler` object from?

**Comment by rafaelsc** [comment]
> I think they referenced this issue by mistake.

Yes. Sorry about that. Was my mistake.

**Comment by Methuselah96** [comment]
Closing for now since I don't think this is an issue with the types, feel free to comment if you would like it to be reopened.
