### ISSUE TITLE
Getting TS error about a property `does not exist on type 'Material | Material[]'`

### ISSUE THREAD

**Issue by benjaminboruff** [three-types/three-ts-types#94]
### What is your question:
I'm new to TS and three.js so I must be missing something basic. I can't figure out why I'm getting this error

```
index.ts:4:15 - error TS2339: Property 'depthTest' does not exist on type 'Material | Material[]'.
Property 'depthTest' does not exist on type 'Material[]'.

4 axes.material.depthTest = false;  // error Property 'depthTest' does not exist on type 'Material | Material[]'.
```

I was converting a working *plain js* version of a three.js tutorial to ts, and fixed all of the issues but this one. I've googled the heck out it ... I setup a simple program to simplify the issue, but I'm still stumped!

index.js
```
import * as THREE from "three";

const axes = new THREE.AxesHelper();
axes.material.depthTest = false;  // error Property 'depthTest' does not exist on type 'Material | Material[]'.
                                  // Property 'depthTest' does not exist on type 'Material[]'.
```

It seems to freak-out on the line from `LineSegments.d.ts`, maybe?
`TMaterial extends Material | Material[] = Material | Material[]`

Honestly, I'm confused by the `|` ... If I comment out the last `| Material[]`  (e.g. `// | Material[]`) then the error goes away.
So, I'm confused :( Can't figure out what I'm doing wrong. Any info would be great!

(Oh, and it still compiles and runs fine despite the ts error!)
Thanks!

Using `node 16.3.0`

package.json
```
{
  "dependencies": {
    "three": "^0.129.0",
    "typescript": "^4.3.2"
  },
  "devDependencies": {
    "@types/node": "^15.12.2",
    "@types/three": "^0.129.1"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "ES2016"
  }
}
```

**Comment by joshuaellis** [comment]
Hey @benjaminboruff, so the type of `material` on `Line` (AxesHelper inherits Line somewhere down the line) is `Material | Material[]` because it can either have an array of materials OR just a singular one, thats what the `|` means, different syntax to vanilla js.

Most classes that do `Material | Material[]` we've made `generics` which means you can pass the material through so you dont run into these issues, there are exceptions where it's not possible – `AxesHelper` being one of these. Therefore you'd have to 'typecast` the result:

```js
(axes.material as Material).depthTest = false
```

If you know the actual material it uses, e.g. `MeshStandardMaterial` you could use that to typecast instead if you were accessing properties specific to `MeshStandardMaterial`. Hope this makes sense?

**Comment by benjaminboruff** [comment]
@joshuaellis Perfect! Thanks!
